apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mediawiki-deploy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service_name: mediawiki
    spec:
      containers:
        - name: mediawiki
          image: wikimedia/mediawiki
          ports:
            - containerPort: 80
         env:
            - name: MYSQL_ROOT_DBUSER
              valueFrom:
                secretKeyRef: 
                  name: mysecret
                  key: MEDIAWIKI_DBUSER
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef: 
                  name: mysecret
                  key: MEDIAWIKI_DBPASSWORD
            - name: MEDIAWIKI_DB_HOST
              value: mysql-svc
          volumeMounts:
            - name: mediawiki-storage
              mountPath: /data
      volumes:
        - name: mediawiki-storage
          hostPath:
            path: /var/lib/mediawiki-containers/mediawiki

---
apiVersion: v1
kind: Service
metadata:
  name: mediawiki-svc
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    service_name: mediawiki